# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 080c609cd836fa27cf1658960d6cb5814e443ec562d517fafd50c76cf69c2bc3baa2c3592f643a11bb2a9edef5cfb7745ecf408ff0b485ac6f1145d79ec5bccf

test:
  secret_key_base: 6efd70013ee82213de2f0e053fa1c414b1212f767de58a5892bb52209bdf7d764c25acb7f09a405078f50b5d94152f74437c569c8886cae0a8a9f55b31d11df4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
